### ISSUE TITLE
I cannot click on next when I select all the execution Indicator

### ISSUE THREAD

**Issue by danielrcardenas** [MdAkramKhanJehad/Software-project-lab-3#3]
I just have one routine then i fill all the options for the routine at the execution indicator. The next button reminds disabled.

<img width="1714" alt="image" src="https://user-images.githubusercontent.com/1779831/192647575-ad5fb6b2-8937-44fc-8cf6-0d406a24dd0b.png">

**Comment by MdAkramKhanJehad** [comment]
solved!
